### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by siavashMehran** [faezemoradi8993/react-students#1]
it will be very beneficial if you would include some pictures in the `README.md` showing how the project looks like.
the majority of people won't go through the whole process of cloning and running a project.

also, can i ask what tool did you use to create the `README.md` ?

**Comment by faezemoradi8993** [comment]
hi dear Siavash , thanks for your suggestion . it was very usefull for me .
i used gitHub descktop to create this repository and  i guess README.md created with this program .i didnot pay attention README.md file before :))) hahaha thanks .

**Comment by faezemoradi8993** [comment]
> it will be very beneficial if you would include some pictures in the `README.md` showing how the project looks like.
> the majority of people won't go through the whole process of cloning and running a project.
> 
> also, can i ask what tool did you use to create the `README.md` ?

hi dear Siavash , thanks for your suggestion . it was very usefull for me .
i used gitHub descktop to create this repository and i guess README.md created with this program .i didnot pay attention README.md file before :))) hahaha thanks .

**Comment by siavashMehran** [comment]
😄
